// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import bo "ic-service/app/model/bo"

import mock "github.com/stretchr/testify/mock"
import request "ic-service/app/model/request"

// IcecreamBuilderInterface is an autogenerated mock type for the IcecreamBuilderInterface type
type IcecreamBuilderInterface struct {
	mock.Mock
}

// IcecreamBuilder provides a mock function with given fields: _a0
func (_m *IcecreamBuilderInterface) IcecreamBuilder(_a0 request.IcecreamRequest) *bo.Icecream {
	ret := _m.Called(_a0)

	var r0 *bo.Icecream
	if rf, ok := ret.Get(0).(func(request.IcecreamRequest) *bo.Icecream); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bo.Icecream)
		}
	}

	return r0
}

// IcecreamPartialBuilder provides a mock function with given fields: _a0, _a1
func (_m *IcecreamBuilderInterface) IcecreamPartialBuilder(_a0 request.IcecreamUpdateRequest, _a1 *bo.Icecream) *bo.Icecream {
	ret := _m.Called(_a0, _a1)

	var r0 *bo.Icecream
	if rf, ok := ret.Get(0).(func(request.IcecreamUpdateRequest, *bo.Icecream) *bo.Icecream); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bo.Icecream)
		}
	}

	return r0
}
