server:
  port: ":5050"

postgres:
  host: "localhost:5432"
  username: "postgres"
  password: "postgres"
  database: "zalora"
  poolsize: 10
  readTimeout: 60000
  writeTimeout: 60000

kafka:
  brokers:
    - "localhost:9092"
  icecreamcreatetopic: "ice_cream_create_dev"
