// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import bo "ic-service/app/model/bo"
import context "context"

import mock "github.com/stretchr/testify/mock"

// SendMessageToKafkaHandler is an autogenerated mock type for the SendMessageToKafkaHandler type
type SendMessageToKafkaHandler struct {
	mock.Mock
}

// SendMessage provides a mock function with given fields: ctx, icecream, isDeleted
func (_m *SendMessageToKafkaHandler) SendMessage(ctx context.Context, icecream *bo.Icecream, isDeleted bool) error {
	ret := _m.Called(ctx, icecream, isDeleted)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *bo.Icecream, bool) error); ok {
		r0 = rf(ctx, icecream, isDeleted)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
